trigger:
- main  # Runs on commits to the main branch

pool:
  name: 'azureagent'  # Use 'ubuntu-latest' for Microsoft-hosted agents

stages:
- stage: Build
  displayName: "Build Java App"
  jobs:
  - job: Build
    steps:
    - script: mvn clean package
      displayName: 'Build and Package the Application'
      
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'target/*.jar'
        artifactName: 'drop'