trigger:
  branches:
    include:
      - main

pool:
  name: 'azureagent'  # Change to 'Azure Pipelines' if using MS-hosted agent

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      disableDownloadFromRegistry: true
      addToPath: false
      architecture: 'x64'

  - script: |
      python3 -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python3 -m unittest discover
    displayName: 'Run Tests'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
