# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: azureagent

#steps:
#- script: echo Hello, world!
 # displayName: 'Run a one-line script'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
              versionSpec: '3.x'
              disableDownloadFromRegistry: false
              addToPath: true
      

    - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
      displayName: "Install Dependencies"

    - script: |
              python -m unittest discover -s tests
      displayName: "Run Unit Tests"

    - script: |
              zip -r $(Build.ArtifactStagingDirectory)/python_app.zip .
      displayName: "Package Application"
